[DIRECTORY]
# Ubah alamat folder sesuai bulan
pusat=\\192.168.50.88\e\back up 21 maret 22\Public\LAP KEU\Tahun 2026\MUTASI\BCA\FEB
depo=\\192.168.50.88\e\back up 21 maret 22\Public\LAP KEU\Tahun 2026\MUTASI\BCA CABANG\FEB
bri=\\192.168.50.88\e\back up 21 maret 22\Public\LAP KEU\Tahun 2026\MUTASI\BRI\FEB

[BANK_MAPPING]
# Khusus BRI
123456789 = SOLO
987654321 = PALU

[EMAIL]
# Password menggunakan fitur Sandi Aplikasi Google dan Verifikasi 2 langkah aktif
# Gunakan ini saja bila perlu
PENGIRIM = me@ihfandicahyo.com
PASSWORD = xxxx xxxx xxxx xxxx

[PENERIMA]
# Tambahkan penerima BCA di bawah, python melihat pola akhir dari nomor rekening
1234 = 1234@ihfandicahyo.com
4567 = 4567@ihfandicahyo.com
8910 = 8910@ihfandicahyo.com
SOLO = solo@ihfandicahyo.com
PALU = palu@ihfandicahyo.com

[ISI EMAIL]
# Isi surel, ubah jika perlu \n\n adalah kode baris baru
SUBJECT = Laporan Mutasi {kode} - Bulan {bulan}
CONTENT = Halo,\n\nBerikut adalah file mutasi {nama_file} yang telah diproses.\n\nTerima kasih.

